### ISSUE TITLE
Question about order of InputArtifacts

### ISSUE THREAD

**Issue by bruce-szalwinski** [tooltwist/codepipeline-artifact-munge#5]
In my CodePipeline CloudFormation template, I've defined the InputParameters as:

            InputArtifacts:
              - Name: BConfigArtifact
              - Name: ZSourceArtifact

When I look at the CloudWatch logs produced by the lambda, I see that the array of InputParameters is given as:

            "inputArtifacts": [
                {
                    "location": {
                        "type": "S3",
                        "s3Location": {
                            "objectKey": "apollo-pipeline-simp/ZSourceArt/MJbMEIt.zip",
                            "bucketName": "csdisco-pipeline-artifacts"
                        }
                    },
                    "revision": "7btAsJ2OsVHgnl81h._Z1Xsn82e7lKqL",
                    "name": "ZSourceArtifact"
                },
                {
                    "location": {
                        "type": "S3",
                        "s3Location": {
                            "objectKey": "apollo-pipeline-simp/BConfigArt/7xRt77p.zip",
                            "bucketName": "csdisco-pipeline-artifacts"
                        }
                    },
                    "revision": "d8eddfa57fb7860647a737334ebca6484344b536",
                    "name": "BConfigArtifact"
                }
            ],

Which is to say that the first InputParameter in the template is the second one in the array and vice versa.  I've run the pipeline numerous times and they always appear in this order.  I changed the names of the InputArtifacts to `BConfigArtifact` and `ASourceArtifact` and `BConfigArtifact` was always first element in event array, no matter the position in the CFn template.  It is as if the inputs are being reverse sorted based on their name.

Did I mess something up with the CloudFormation template?

**Comment by bruce-szalwinski** [comment]
For giggles, 

            InputArtifacts:
              - Name: BConfigArtifact
              - Name: YConfigArtifact
              - Name: ZSourceArtifact

Becomes:

           "inputArtifacts": [
                {
                    "location": {
                        "type": "S3",
                        "s3Location": {
                            "objectKey": "apollo-pipeline-simp/YConfigArt/1ck2jz2.zip",
                            "bucketName": "csdisco-pipeline-artifacts"
                        }
                    },
                    "revision": "d8eddfa57fb7860647a737334ebca6484344b536",
                    "name": "YConfigArtifact"
                },
                {
                    "location": {
                        "type": "S3",
                        "s3Location": {
                            "objectKey": "apollo-pipeline-simp/ZSourceArt/gOlM6rK.zip",
                            "bucketName": "csdisco-pipeline-artifacts"
                        }
                    },
                    "revision": "7btAsJ2OsVHgnl81h._Z1Xsn82e7lKqL",
                    "name": "ZSourceArtifact"
                },
                {
                    "location": {
                        "type": "S3",
                        "s3Location": {
                            "objectKey": "apollo-pipeline-simp/BConfigArt/EWDdUN5.zip",
                            "bucketName": "csdisco-pipeline-artifacts"
                        }
                    },
                    "revision": "d8eddfa57fb7860647a737334ebca6484344b536",
                    "name": "BConfigArtifact"
                }
            ],

So it seems rather arbitrary on how InputParameters in CFn get passed to Lambda.

**Comment by Phrozyn** [comment]
I realize this is pretty late, but if others run across this:

There is a specification of RunOrder which will indicate the order to run.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codepipeline-pipeline-stages-actions.html
